// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bonus.djinni

#import "SDBonusModel.h"
#include "bonus_model.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SDBonusModel;

namespace djinni_generated {

struct BonusModel
{
    using CppType = ::BonusModel;
    using ObjcType = SDBonusModel*;

    using Boxed = BonusModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
