// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from color.djinni

#import "SDColorModel+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ColorModel::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.red),
            ::djinni::I32::toCpp(obj.green),
            ::djinni::I32::toCpp(obj.blue)};
}

auto ColorModel::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SDColorModel alloc] initWithRed:(::djinni::I32::fromCpp(cpp.red))
                                       green:(::djinni::I32::fromCpp(cpp.green))
                                        blue:(::djinni::I32::fromCpp(cpp.blue))];
}

}  // namespace djinni_generated
