// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from color.djinni

#import "SDColorModel.h"
#include "color_model.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SDColorModel;

namespace djinni_generated {

struct ColorModel
{
    using CppType = ::ColorModel;
    using ObjcType = SDColorModel*;

    using Boxed = ColorModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
