// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from field.djinni

#import "SDField.h"
#include "field.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SDField;

namespace djinni_generated {

struct Field
{
    using CppType = ::Field;
    using ObjcType = SDField*;

    using Boxed = Field;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
