// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from game.djinni

#import "SDGame+Private.h"
#import "SDGame.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SDField+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SDGame ()

- (id)initWithCpp:(const std::shared_ptr<::Game>&)cppRef;

@end

@implementation SDGame {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::Game>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Game>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SDGame *)instance {
    try {
        auto objcpp_result_ = ::Game::Instance();
        return ::djinni_generated::Game::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)enter {
    try {
        _cppRefHandle.get()->Enter();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)run {
    try {
        _cppRefHandle.get()->Run();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setDirection:(int32_t)dx
                  dy:(int32_t)dy {
    try {
        _cppRefHandle.get()->SetDirection(::djinni::I32::toCpp(dx),
                                          ::djinni::I32::toCpp(dy));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull SDField *)getField {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->GetField();
        return ::djinni_generated::Field::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Game::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Game::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SDGame>(cpp);
}

}  // namespace djinni_generated

@end
