// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from point.djinni

#import "SDPoint+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Point::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.x),
            ::djinni::I32::toCpp(obj.y)};
}

auto Point::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SDPoint alloc] initWithX:(::djinni::I32::fromCpp(cpp.x))
                                    y:(::djinni::I32::fromCpp(cpp.y))];
}

}  // namespace djinni_generated
