// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from snake.djinni

#import "SDSnakeModel+Private.h"
#import "DJIMarshal+Private.h"
#import "SDVectorModel+Private.h"
#include <cassert>

namespace djinni_generated {

auto SnakeModel::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::List<::djinni_generated::VectorModel>::toCpp(obj.points),
            ::djinni_generated::VectorModel::toCpp(obj.leftEye),
            ::djinni_generated::VectorModel::toCpp(obj.rightEye)};
}

auto SnakeModel::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SDSnakeModel alloc] initWithPoints:(::djinni::List<::djinni_generated::VectorModel>::fromCpp(cpp.points))
                                        leftEye:(::djinni_generated::VectorModel::fromCpp(cpp.left_eye))
                                       rightEye:(::djinni_generated::VectorModel::fromCpp(cpp.right_eye))];
}

}  // namespace djinni_generated
