// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from snake.djinni

#import "SDSnakeModel.h"
#include "snake_model.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SDSnakeModel;

namespace djinni_generated {

struct SnakeModel
{
    using CppType = ::SnakeModel;
    using ObjcType = SDSnakeModel*;

    using Boxed = SnakeModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
