// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vector.djinni

#import "SDVectorModel.h"
#include "vector_model.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SDVectorModel;

namespace djinni_generated {

struct VectorModel
{
    using CppType = ::VectorModel;
    using ObjcType = SDVectorModel*;

    using Boxed = VectorModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
