// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from walls.djinni

#import "SDWalls.h"
#include "walls.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SDWalls;

namespace djinni_generated {

struct Walls
{
    using CppType = ::Walls;
    using ObjcType = SDWalls*;

    using Boxed = Walls;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
