// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vector.djinni

#pragma once

#include "djinni_support.hpp"
#include "vector_model.hpp"

namespace djinni_generated {

class NativeVectorModel final {
public:
    using CppType = ::VectorModel;
    using JniType = jobject;

    using Boxed = NativeVectorModel;

    ~NativeVectorModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeVectorModel();
    friend ::djinni::JniClass<NativeVectorModel>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("ru/tensor/generated/VectorModel") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(FF)V") };
    const jfieldID field_mX { ::djinni::jniGetFieldID(clazz.get(), "mX", "F") };
    const jfieldID field_mY { ::djinni::jniGetFieldID(clazz.get(), "mY", "F") };
};

}  // namespace djinni_generated
