// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vector.djinni

#include "NativeVectorModel.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeVectorModel::NativeVectorModel() = default;

NativeVectorModel::~NativeVectorModel() = default;

auto NativeVectorModel::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeVectorModel>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.x)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.y)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeVectorModel::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeVectorModel>::get();
    return {::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mX)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mY))};
}

}  // namespace djinni_generated
