// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from point.djinni

#pragma once

#include "djinni_support.hpp"
#include "point.hpp"

namespace djinni_generated {

class NativePoint final {
public:
    using CppType = ::Point;
    using JniType = jobject;

    using Boxed = NativePoint;

    ~NativePoint();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativePoint();
    friend ::djinni::JniClass<NativePoint>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("ru/tensor/generated/Point") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(II)V") };
    const jfieldID field_mX { ::djinni::jniGetFieldID(clazz.get(), "mX", "I") };
    const jfieldID field_mY { ::djinni::jniGetFieldID(clazz.get(), "mY", "I") };
};

}  // namespace djinni_generated
