// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from game.djinni

#pragma once

#include "djinni_support.hpp"
#include "game.hpp"

namespace djinni_generated {

class NativeGame final : ::djinni::JniInterface<::Game, NativeGame> {
public:
    using CppType = std::shared_ptr<::Game>;
    using CppOptType = std::shared_ptr<::Game>;
    using JniType = jobject;

    using Boxed = NativeGame;

    ~NativeGame();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeGame>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeGame>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeGame();
    friend ::djinni::JniClass<NativeGame>;
    friend ::djinni::JniInterface<::Game, NativeGame>;

};

}  // namespace djinni_generated
