// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from game.djinni

#include "NativeGame.hpp"  // my header
#include "Marshal.hpp"
#include "NativeField.hpp"

namespace djinni_generated {

NativeGame::NativeGame() : ::djinni::JniInterface<::Game, NativeGame>("ru/tensor/generated/Game$CppProxy") {}

NativeGame::~NativeGame() = default;


CJNIEXPORT void JNICALL Java_ru_tensor_generated_Game_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::Game>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ru_tensor_generated_Game_instance(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::Game::Instance();
        return ::djinni::release(::djinni_generated::NativeGame::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ru_tensor_generated_Game_00024CppProxy_native_1enter(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::Game>(nativeRef);
        ref->Enter();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ru_tensor_generated_Game_00024CppProxy_native_1run(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jfloat j_dispWidth, jfloat j_dispHeight)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::Game>(nativeRef);
        ref->Run(::djinni::F32::toCpp(jniEnv, j_dispWidth),
                 ::djinni::F32::toCpp(jniEnv, j_dispHeight));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ru_tensor_generated_Game_00024CppProxy_native_1setDirection(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_dx, jint j_dy)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::Game>(nativeRef);
        ref->SetDirection(::djinni::I32::toCpp(jniEnv, j_dx),
                          ::djinni::I32::toCpp(jniEnv, j_dy));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ru_tensor_generated_Game_00024CppProxy_native_1getField(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::Game>(nativeRef);
        auto r = ref->GetField();
        return ::djinni::release(::djinni_generated::NativeField::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
