// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from snake.djinni

#include "NativeSnakeModel.hpp"  // my header
#include "Marshal.hpp"
#include "NativePoint.hpp"

namespace djinni_generated {

NativeSnakeModel::NativeSnakeModel() = default;

NativeSnakeModel::~NativeSnakeModel() = default;

auto NativeSnakeModel::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSnakeModel>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::List<::djinni_generated::NativePoint>::fromCpp(jniEnv, c.points)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSnakeModel::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSnakeModel>::get();
    return {::djinni::List<::djinni_generated::NativePoint>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mPoints))};
}

}  // namespace djinni_generated
