// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from walls.djinni

#pragma once

#include "djinni_support.hpp"
#include "walls.hpp"

namespace djinni_generated {

class NativeWalls final {
public:
    using CppType = ::Walls;
    using JniType = jobject;

    using Boxed = NativeWalls;

    ~NativeWalls();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeWalls();
    friend ::djinni::JniClass<NativeWalls>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("ru/tensor/generated/Walls") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(IIII)V") };
    const jfieldID field_mLeftX { ::djinni::jniGetFieldID(clazz.get(), "mLeftX", "I") };
    const jfieldID field_mTopY { ::djinni::jniGetFieldID(clazz.get(), "mTopY", "I") };
    const jfieldID field_mRightX { ::djinni::jniGetFieldID(clazz.get(), "mRightX", "I") };
    const jfieldID field_mBottomY { ::djinni::jniGetFieldID(clazz.get(), "mBottomY", "I") };
};

}  // namespace djinni_generated
