// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bonus.djinni

#import "SDBonusModel.h"


@implementation SDBonusModel

- (nonnull instancetype)initWithPosition:(nonnull SDVectorModel *)position
                                   color:(nonnull SDColorModel *)color
{
    if (self = [super init]) {
        _position = position;
        _color = color;
    }
    return self;
}

+ (nonnull instancetype)bonusModelWithPosition:(nonnull SDVectorModel *)position
                                         color:(nonnull SDColorModel *)color
{
    return [[self alloc] initWithPosition:position
                                    color:color];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p position:%@ color:%@>", self.class, (void *)self, self.position, self.color];
}

@end
