// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bonus.djinni

#import "SDColorModel.h"
#import "SDVectorModel.h"
#import <Foundation/Foundation.h>

@interface SDBonusModel : NSObject
- (nonnull instancetype)initWithPosition:(nonnull SDVectorModel *)position
                                   color:(nonnull SDColorModel *)color;
+ (nonnull instancetype)bonusModelWithPosition:(nonnull SDVectorModel *)position
                                         color:(nonnull SDColorModel *)color;

@property (nonatomic, readonly, nonnull) SDVectorModel * position;

@property (nonatomic, readonly, nonnull) SDColorModel * color;

@end
