// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from color.djinni

#import <Foundation/Foundation.h>

@interface SDColorModel : NSObject
- (nonnull instancetype)initWithRed:(int32_t)red
                              green:(int32_t)green
                               blue:(int32_t)blue;
+ (nonnull instancetype)colorModelWithRed:(int32_t)red
                                    green:(int32_t)green
                                     blue:(int32_t)blue;

@property (nonatomic, readonly) int32_t red;

@property (nonatomic, readonly) int32_t green;

@property (nonatomic, readonly) int32_t blue;

@end
