// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from color.djinni

#import "SDColorModel.h"


@implementation SDColorModel

- (nonnull instancetype)initWithRed:(int32_t)red
                              green:(int32_t)green
                               blue:(int32_t)blue
{
    if (self = [super init]) {
        _red = red;
        _green = green;
        _blue = blue;
    }
    return self;
}

+ (nonnull instancetype)colorModelWithRed:(int32_t)red
                                    green:(int32_t)green
                                     blue:(int32_t)blue
{
    return [[self alloc] initWithRed:red
                               green:green
                                blue:blue];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p red:%@ green:%@ blue:%@>", self.class, (void *)self, @(self.red), @(self.green), @(self.blue)];
}

@end
