// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from field.djinni

#import "SDBonusModel.h"
#import "SDSnakeModel.h"
#import "SDWalls.h"
#import <Foundation/Foundation.h>

@interface SDField : NSObject
- (nonnull instancetype)initWithWalls:(nonnull SDWalls *)walls
                               snakes:(nonnull NSArray<SDSnakeModel *> *)snakes
                              mySnake:(nullable SDSnakeModel *)mySnake
                              bonuses:(nonnull NSArray<SDBonusModel *> *)bonuses;
+ (nonnull instancetype)fieldWithWalls:(nonnull SDWalls *)walls
                                snakes:(nonnull NSArray<SDSnakeModel *> *)snakes
                               mySnake:(nullable SDSnakeModel *)mySnake
                               bonuses:(nonnull NSArray<SDBonusModel *> *)bonuses;

@property (nonatomic, readonly, nonnull) SDWalls * walls;

@property (nonatomic, readonly, nonnull) NSArray<SDSnakeModel *> * snakes;

@property (nonatomic, readonly, nullable) SDSnakeModel * mySnake;

@property (nonatomic, readonly, nonnull) NSArray<SDBonusModel *> * bonuses;

@end
