// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from game.djinni

#import "SDField.h"
#import <Foundation/Foundation.h>
@class SDGame;


@interface SDGame : NSObject

+ (nullable SDGame *)instance;

- (void)enter;

- (void)run;

- (void)setDirection:(int32_t)dx
                  dy:(int32_t)dy;

- (nonnull SDField *)getField;

@end
