// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from point.djinni

#import <Foundation/Foundation.h>

@interface SDPoint : NSObject
- (nonnull instancetype)initWithX:(int32_t)x
                                y:(int32_t)y;
+ (nonnull instancetype)pointWithX:(int32_t)x
                                 y:(int32_t)y;

@property (nonatomic, readonly) int32_t x;

@property (nonatomic, readonly) int32_t y;

@end
