// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from snake.djinni

#import "SDSnakeModel.h"


@implementation SDSnakeModel

- (nonnull instancetype)initWithPoints:(nonnull NSArray<SDVectorModel *> *)points
                               leftEye:(nonnull SDVectorModel *)leftEye
                              rightEye:(nonnull SDVectorModel *)rightEye
{
    if (self = [super init]) {
        _points = [points copy];
        _leftEye = leftEye;
        _rightEye = rightEye;
    }
    return self;
}

+ (nonnull instancetype)snakeModelWithPoints:(nonnull NSArray<SDVectorModel *> *)points
                                     leftEye:(nonnull SDVectorModel *)leftEye
                                    rightEye:(nonnull SDVectorModel *)rightEye
{
    return [[self alloc] initWithPoints:points
                                leftEye:leftEye
                               rightEye:rightEye];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p points:%@ leftEye:%@ rightEye:%@>", self.class, (void *)self, self.points, self.leftEye, self.rightEye];
}

@end
