// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vector.djinni

#import "SDVectorModel.h"


@implementation SDVectorModel

- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
{
    if (self = [super init]) {
        _x = x;
        _y = y;
    }
    return self;
}

+ (nonnull instancetype)vectorModelWithX:(float)x
                                       y:(float)y
{
    return [[self alloc] initWithX:x
                                 y:y];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p x:%@ y:%@>", self.class, (void *)self, @(self.x), @(self.y)];
}

@end
