// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vector.djinni

#import <Foundation/Foundation.h>

@interface SDVectorModel : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y;
+ (nonnull instancetype)vectorModelWithX:(float)x
                                       y:(float)y;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@end
