// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from walls.djinni

#import <Foundation/Foundation.h>

@interface SDWalls : NSObject
- (nonnull instancetype)initWithLeftX:(int32_t)leftX
                                 topY:(int32_t)topY
                               rightX:(int32_t)rightX
                              bottomY:(int32_t)bottomY;
+ (nonnull instancetype)wallsWithLeftX:(int32_t)leftX
                                  topY:(int32_t)topY
                                rightX:(int32_t)rightX
                               bottomY:(int32_t)bottomY;

@property (nonatomic, readonly) int32_t leftX;

@property (nonatomic, readonly) int32_t topY;

@property (nonatomic, readonly) int32_t rightX;

@property (nonatomic, readonly) int32_t bottomY;

@end
